### ISSUE TITLE
Migrate from abandoned SMC codebase to maintained TSC fork

### ISSUE THREAD

**Issue by Bugsbane** [pedja1/SMC-Android#15]
Given that Secret Maryo Chronicles is not developed any more and pretty much all of the active contributors (including myself, Bugsbane / Helios) have moved to contributing to [the Secret Chronicles fork](https://github.com/Secretchronicles/TSC), might I suggest that this project does the same before the codebase varies so much that it becomes difficult to do so later?

Many of the SMC assets are outdated and ugly (or just plain illegal, *cough* Turtle Boss *cough* music *cough*), which is being remedied in TSC along with a stack of great new features. It would be fabulous to see an Android version of the more recent incarnations.

Thanks!

**Comment by pedja1** [comment]
No code from original smc is used in this project, only assets. And event assets are not 100% original. Also gameplay/levels/ui, all of that is rewriten and changed a bit. I dont think that this project can be called fork of the SMC :). 
This is just a project that i started because i wanted to make a game but i didnt want to draw graphics my self. 
It would be nearly impossible to keep up with all of the changes on TSC.

Since TSC support linux, and android is basically linux, i think that someone should try to actullay port existing code for android, and just rewrite ui (because current ui is not touch friendly). I might try to do that if i get some spare time...

**Comment by Bugsbane** [comment]
OK, thanks for claring that up. Just be warnd though that its mainly th art (and som music) assts that are legally questionable. To get a better idea of which ones, take a look at the issues in TSC tagged with "de-marioization".

**Comment by pedja1** [comment]
OK, thanks for the warning about the art...
